config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :songs
  root 'welcome#index'
  get 'search', to: 'songs#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cipher.rb
class Cipher < ApplicationRecord
  belongs_to :Song
  validates_presence_of :word
  validates_numericality_of :bag_id
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    settings index: { number_of_shards: 1 } do
      mapping dynamic: false do
        indexes :title, type: :text, analyzer: 'english'
        indexes :artist, type: :text, analyzer: 'english'
      end
    end

    #def self.search(query)
      # ...
    #end
  end
end

app/models/song.rb
require 'elasticsearch/model'

class Song < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
end

=begin
class Song < ApplicationRecord
  Elasticsearch::Model.client = Elasticsearch::Client.new url: ENV['https://zp7bpiu6:uv3576rppz3es5bu@boxwood-6146436.us-east-1.bonsaisearch.net'], log: true
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Searchable

#  searchable do
#  	text :tid, :mxmid, :title, :artist, :lyrics_hash
#  end
  lyrics_index Rails.application.class.parent_name.underscore
  Song self.name.downcase

end

  def as_indexed_json(options = nil)
    self.as_json({
      only: [:tid, :mxmid, :title, :artist, :lyrics_hash],
      #include: {
      #  artist: { only: :name },
      #  title: { only: :name },
      #}
    })
  end

  def self.search(query)
    __elasticsearch__.search(
    {
      query: {
        multi_match: {
          query: query,
          fields: ['title^5', 'body']
        }
      },
    end
  end



Song.mappings.to_hash
Song.settings.to_hash

def self.search(query)
  __elasticsearch__.search(
    {
      query: {
        multi_match: {
          query: query,
          fields: ['title^10', 'text']
        }
      }
    }
  )
end

=end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    unless params[:query].blank?
      @results = Page.search( params[:query] )
      @songs = @results
    end
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]


  def index
    if params[:search].blank?
      @songs = Song.all.paginate(:page => params[:page], :per_page => 50)
    else
      @songs = Song.__elasticsearch__.search(params[:search]).paginate(:page => params[:page], :per_page => 50).results
    end
  end

  # GET /songs
  # GET /songs.json

=begin
  def index

    if params[:q].nil?
      @songs = []
    else
      @songs = Song.search params[:q] 
    end

    @search = Song.search do
      fulltext params[:search]
      paginate(:page => params[:page])
    end
    # # binding.pry
    @songs = @search.results

    #@songs = Song.first
    #@songs = Song.all
    # binding.pry
    #@songs = Song.first
    #@songs = Song.all
    #@songs = Song.paginate(:page => params[:page])
  end
=end

  def search
    if params[:q].nil?
      @songs = []
    else
      @songs = Song.search(params[:q]).paginate(:page => params[:page], :per_page => 50)
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    #@song = Song.find(params[:id])
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:tid, :mxmid, :lyrics_hash)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Songs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--
  	<%#= form_tag(songs_path, :method => "get", id: "search-form") do %>
      <%#= text_field_tag :search, params[:search], placeholder: "Search Lyrics" %>
      <%#= submit_tag "Search", :name => nil %>
	  <#% end %>
  -->
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
- @results.each do |page|
  article
    h3 = page.title
    - if page.respond_to? :highlight
      p = raw page.highlight.body.to_a.join(' ')
    - else
      p = raw truncate(page.body, length: 300)

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tid %>
    <%= f.text_field :tid %>
  </div>

  <div class="field">
    <%= f.label :mxmid %>
    <%= f.number_field :mxmid %>
  </div>

  <div class="field">
    <%= f.label :lyrics_hash %>
    <%= f.text_area :lyrics_hash %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<%= form_tag(songs_path, :method => "get", id: "search-form", style: "float: left;") do %>

    <%= text_field_tag :search, params[:search], placeholder: "Search Songs" %>
    <%= submit_tag "Search", :name => nil %>



<% end %>

<br>

<table>
  <thead>
    <tr>
      <th>Tid</th>
      <th>Mxmid</th>
      <th>Title</th>
      <th>Artist</th>

      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.tid %></td>
        <td><%= song.mxmid %></td>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>

        <td><%#= link_to 'Show', song %></td>
        <td><%#= link_to 'Edit', edit_song_path(song) %></td>
        <td><%#= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= will_paginate @songs %>

<br>

<%#= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/search.html.erb
<h1>Songs Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @songs.each do |song| %>
    <li>
      <h3>
        <%= link_to song.title, controller: "songs", action: "show", id: song._id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tid:</strong>
  <%= @song.tid %>
</p>

<p>
  <strong>Mxmid:</strong>
  <%= @song.mxmid %>
</p>

<p>
  <strong>Lyrics hash:</strong>
  <%= @song.lyrics_hash %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/welcome/index.html.erb
<h1>Your Songs</h1>
<h3>Access to all your favorite songs right at your fingertips</h3>
<%= form_tag(songs_path, :method => "get", id: "search-form") do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Search Lyrics" %>
    <%= submit_tag "Search", :name => nil %>
  </p>	  
<% end %>